### PR TITLE
Add official support for Django 5.0 and Python 3.12, drop support for Django <3.2

### PR DESCRIPTION
**Pull request by browniebroke**

### CODE REVIEW

**Comment by browniebroke** [comment]
As far as I can tell, the failures are from mypy, looks like the config crashes:

```
mypy.ini:2: error: Error importing plugin "mypy_django_plugin.main": cannot import name 'has_placeholder' from 'mypy.semanal_shared' (...python3.11/site-packages/mypy/semanal_shared.py)
```

It fails on older versions too, so maybe it's a 3rd party package not being pinned properly?

**Comment by browniebroke** [comment]
Gentle ping @ir4y - what do we need to get this merged?

**Comment by ir4y** [comment]
Hi @browniebroke 

Thank you for your contribution. Could you please fix the tests?
Once all of them are passed I will merge this changes.

Cheers,
Ilya

**Comment by ir4y** [comment]
@browniebroke please feel free to include changes from https://github.com/beda-software/drf-writable-nested/pull/184 in this pull request and drop support for Django version that reached end of support period.

**Comment by browniebroke** [comment]
@ir4y it's all passing now. Since I opened this, Django 3.2 reached EOL and DRF 3.15 was released. I could go a few steps further and drop support for Django <4.2 (which would mean dropping DRF <3.14) and add support for DRF 3.15, but that feels like a lot? Do you want to merge this one and do a release before moving on to the next set of fixes? 

I'm trying to think of an upgrade path where users wouldn't have to upgrade too much at once, but actually I didn't really change anything in the code being released...
